#!/bin/bash

# Deployment Script
# Auto-generated by NCU Deployment CLI
set -e

# Default values
ENV="test"
REF="main"
BASE_PATH=""
CONTAINER=""
DOMAIN=""

# Parse arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --env) ENV="$2"; shift ;;
        --ref) REF="$2"; shift ;;
        --base-path) BASE_PATH="$2"; shift ;;
        --container) CONTAINER="$2"; shift ;;
        --domain) DOMAIN="$2"; shift ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

# Validate required arguments
if [ -z "$BASE_PATH" ]; then
    echo "Error: --base-path is required"
    exit 1
fi

echo "Deploying to $ENV environment..."
echo "Ref: $REF"
echo "Base Path: $BASE_PATH"

# Navigate to project directory
cd "$BASE_PATH" || exit 1

# Fetch latest changes
echo "Fetching latest changes..."
git fetch origin

# Checkout specific ref
echo "Checking out $REF..."
git checkout "$REF"
git pull origin "$REF"

# Create .env file if it doesn't exist
if [ ! -f .env ]; then
    echo "Creating .env file..."
    echo "NODE_ENV=$ENV" > .env
    echo "PORT=3000" >> .env
fi

# Create volume directories if they don't exist
echo "Ensuring volume directories exist..."
mkdir -p volumes/data volumes/uploads

# Build and start containers
echo "Building and starting containers..."
export CONTAINER_NAME="${CONTAINER:-app}"
docker compose up -d --build --remove-orphans

# Wait for container to be ready
echo "Waiting for container to be healthy..."
sleep 5

# Run custom migration scripts
if [ -d "scripts/migrations" ] && [ -n "$(ls -A scripts/migrations/*.js 2>/dev/null)" ]; then
    echo "Running custom migration scripts..."
    for migration in scripts/migrations/*.js; do
        echo "  - Running $(basename "$migration")..."
        docker compose exec -T app node "$migration" || echo "  ⚠ Migration $(basename "$migration") had issues"
    done
else
    echo "No migrations detected, skipping..."
fi

# Verify deployment
echo "Verifying deployment..."
if docker compose ps | grep -q "Up"; then
    echo "✅ Container is running"
else
    echo "❌ Container failed to start"
    docker compose logs --tail=50
    exit 1
fi

# Prune old images to save space
echo "Pruning old docker images..."
docker image prune -f

echo "✅ Deployment complete!"
echo "Container: ${CONTAINER_NAME}"
echo "Port: ${PORT:-3001}"
