#!/bin/bash

# Deployment Script
# Auto-generated by NCU Deployment CLI

# Default values
ENV="test"
REF="main"
BASE_PATH=""
CONTAINER=""
DOMAIN=""

# Parse arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --env) ENV="$2"; shift ;;
        --ref) REF="$2"; shift ;;
        --base-path) BASE_PATH="$2"; shift ;;
        --container) CONTAINER="$2"; shift ;;
        --domain) DOMAIN="$2"; shift ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

# Validate required arguments
if [ -z "$BASE_PATH" ]; then
    echo "Error: --base-path is required"
    exit 1
fi

echo "Deploying to $ENV environment..."
echo "Ref: $REF"
echo "Base Path: $BASE_PATH"

# Navigate to project directory
cd "$BASE_PATH" || exit 1

# Fetch latest changes
echo "Fetching latest changes..."
git fetch origin

# Checkout specific ref
echo "Checking out $REF..."
git checkout "$REF"
git pull origin "$REF"

# Create .env file if it doesn't exist (or update it)
if [ ! -f .env ]; then
    echo "Creating .env file..."
    echo "NODE_ENV=$ENV" > .env
    echo "PORT=3000" >> .env
fi

# Build and start containers
# Build and start containers
echo "Building and starting containers..."
export CONTAINER_NAME="$CONTAINER"
docker compose up -d --build --remove-orphans

# Run migrations if the script exists
if [ -f "scripts/migrate.sh" ]; then
    echo "Running migrations..."
    ./scripts/migrate.sh
elif [ -f "prisma/schema.prisma" ]; then
    echo "Detected Prisma, running migrations..."
    docker compose exec -T app npx prisma migrate deploy
fi

# Prune old images to save space
echo "Pruning old docker images..."
docker image prune -f

echo "Deployment complete!"
